export class StorageKeys {
  static readonly TOKEN: string = 'token';
  static readonly USER_ID: string = 'userId';
  static readonly ROLE: string = 'role';
  static readonly REAL_NAME: string = 'realName';
  static readonly ELDERLY_ID: string = 'elderlyId';
  static readonly ELDERLY_NAME: string = 'elderlyName';
  static readonly COMMUNITY_ID: string = 'communityId';
  static readonly COMMUNITY_NAME: string = 'communityName';
  static readonly LATEST_SOS_ALERT_ID: string = 'latestSosAlertId';
  static readonly UNREAD_ALERT_COUNT: string = 'unreadAlertCount';
  static readonly HAS_NEW_SOS_ALERT: string = 'hasNewSosAlert';
}
